[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rust"
path = "src/main.rs"

[package.metadata]
default-run = "rust"

[dependencies]
postgres = "0.19"
actix-web = "4"
diesel = {version="2.0.0", features = ["postgres"]}
dotenvy = "0.15"